services:
  tests:
    build: ./tests
    environment:
      SSH_HOST: sshgateway
      SSH_PORT: 22
      KEYS_DIR: /keys
    depends_on:
      sshgateway:
        condition: service_healthy
    volumes:
      - ssh_keys:/keys
    command: ["/bin/sh", "/app/run_tests.sh"]